In [1]:
import numpy as np
import json

In [2]:
from config.config import top_features_750
import pandas as pd
app_test=pd.read_parquet('data/processed/final_test.parquet')

In [3]:
lookup_df=pd.read_parquet('api/data/lookup_df.parquet')

In [4]:
lookup_df

,SK_ID_CURR,base_value,shap_ORGANIZATION_TYPE,shap_credit_to_annuity,shap_goods_to_credit,shap_EXT_SOURCE_3,shap_EXT_SOURCE_1,shap_DAYS_LAST_PHONE_CHANGE,shap_AMT_ANNUITY,shap_ext_std,...,shap_BUREAU_BB_CURR_STAT_MAX,shap_ACTIVE_BUREAU_B_OVERDUE_TO_DEBT_STD,shap_BUREAU_BB_MISSING_MEAN,shap_total_microloan_overdue,shap_FLAG_OWN_CAR_BIN,shap_BUREAU_B_ACTIVE_OVERDUE_MAX,shap_ACTIVE_BUREAU_B_RECENT_30D_SUM,shap_CLOSED_BUREAU_BB_CURR_STAT_MAX,shap_ACTIVE_BUREAU_BB_SMA1_RATIO_MEAN,shap_ACTIVE_BUREAU_B_DPD30_FLAG_MEAN
0,100001,-2.970138,-0.104212,-0.032564,0.113071,0.092327,-0.007009,-0.021129,-0.053612,0.020631,...,0.0,-0.000007,0.000009,0.0,-0.000838,-2.501547e-06,0.0,0.0,0.000011,0.000051
1,100005,-2.970138,0.134332,0.029410,0.103048,0.017726,-0.061202,0.030962,-0.041262,-0.006055,...,0.0,-0.000009,0.000011,0.0,0.000240,-1.360905e-06,0.0,0.0,0.000011,0.000046
2,100013,-2.970138,0.412998,-0.336846,-0.095830,0.003598,0.016243,0.013794,0.041553,-0.010591,...,0.0,0.000016,0.000015,0.0,-0.001157,-9.866442e-07,0.0,0.0,0.000011,0.000051
3,100028,-2.970138,0.022552,0.007108,-0.170421,-0.019873,-0.080060,-0.018080,0.079948,-0.004898,...,0.0,-0.000010,0.000027,0.0,-0.000239,-2.519671e-06,0.0,0.0,0.000007,0.000051
4,100038,-2.970138,0.096776,0.120347,-0.155179,-0.112638,-0.015536,0.026421,0.096872,-0.008550,...,0.0,0.000008,0.000012,0.0,-0.000278,-1.369153e-06,0.0,0.0,0.000011,0.000049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48739,456221,-2.970138,-0.053662,-0.070903,0.224630,-0.012389,0.005422,0.014089,-0.082047,0.057815,...,0.0,-0.000015,0.000016,0.0,0.000155,-1.394387e-06,0.0,0.0,0.000011,0.000045
48740,456222,-2.970138,-0.006099,0.147073,0.116305,-0.058659,0.084455,0.079966,0.091918,0.034036,...,0.0,0.000012,0.000025,0.0,0.000261,-2.486275e-06,0.0,0.0,0.000011,0.000049
48741,456223,-2.970138,0.033301,-0.457714,-0.086051,0.046003,-0.025826,0.021983,0.065171,-0.010804,...,0.0,0.000009,0.000048,0.0,-0.000842,-1.511795e-06,0.0,0.0,0.000007,0.000049
48742,456224,-2.970138,0.073111,-0.088041,-0.115186,-0.021181,-0.068018,-0.032275,0.002827,-0.008100,...,0.0,0.000007,0.000006,0.0,0.000251,-1.367807e-06,0.0,0.0,0.000011,0.000049
48743,456250,-2.970138,-0.068069,0.333212,0.057189,0.082271,0.050679,0.024208,0.010547,-0.013982,...,0.0,-0.000003,0.000637,0.0,-0.000137,-2.486275e-06,0.0,0.0,0.000011,0.000046

In [5]:
app_test

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,mortgage_debt_share,total_microloan_debt,total_microloan_count,total_microloan_overdue,total_microloan_max_overdue,microloan_overdue_to_typedebt,microloan_max_overdue_to_typedebt,microloan_overdue_to_total,microloan_max_overdue_to_total,microloan_debt_share
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48739,456221,Cash loans,F,N,Y,0,121500.0,412560.0,17473.5,270000.0,...,NaN,18000.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48740,456222,Cash loans,F,N,N,2,157500.0,622413.0,31909.5,495000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48741,456223,Cash loans,F,Y,Y,1,202500.0,315000.0,33205.5,315000.0,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48742,456224,Cash loans,M,N,N,0,225000.0,450000.0,25128.0,450000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48743,456250,Cash loans,F,Y,N,0,135000.0,312768.0,24709.5,270000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
features=top_features_750