In [81]:
import pandas as pd
import numpy as np

In [82]:
bureau_fe=pd.read_csv('/Users/rageshwer/Goal ML/Projects/Home_Credit_Default_Risk/data/interim/bureau_fe.csv')
bb_fe=pd.read_csv('/Users/rageshwer/Goal ML/Projects/Home_Credit_Default_Risk/data/interim/bb_fe.csv')

In [83]:
print(bureau_fe.shape)
print(bureau_fe['SK_ID_BUREAU'].nunique())

(1716428, 86)
1716428

In [84]:
print(bb_fe.shape)
print(bb_fe['SK_ID_BUREAU'].nunique())

(817395, 17)
817395

In [85]:
bureau_fe['SK_ID_BUREAU'].isin(
    bb_fe['SK_ID_BUREAU']
).mean()*100

np.float64(45.114272197843434)

In [86]:
bureau_master=bureau_fe.merge(bb_fe,on='SK_ID_BUREAU',how='left')

In [87]:
bureau_master

,Unnamed: 0_x,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,...,bb_curr_stat,bb_mean_dpd,bb_sma0,bb_sma1,bb_sma2,bb_npa,bb_sma0_ratio,bb_sma1_ratio,bb_sma2_ratio,bb_npa_ratio
0,0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1716424,1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1716425,1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1716426,1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1716427,1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
bureau_master.select_dtypes(exclude='number').columns

Index(['CREDIT_ACTIVE', 'CREDIT_CURRENCY', 'CREDIT_TYPE'], dtype='str')

In [89]:
bureau_master['SK_ID_CURR'].nunique()

305811

In [90]:
# the ratios might have large values
bureau_master.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

,Unnamed: 0_x,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,...,bb_curr_stat,bb_mean_dpd,bb_sma0,bb_sma1,bb_sma2,bb_npa,bb_sma0_ratio,bb_sma1_ratio,bb_sma2_ratio,bb_npa_ratio
0,0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1716424,1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1716425,1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1716426,1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1716427,1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

So, now we have 102 features brom bureau and bureau balance. Now we need to group this master loan data file according to the customer id's and aggregate the features present. The major step now is to identify how to aggregate each of these features i.e which feature requires simple counts and what needs mean, max, min, count, sum.<br>
I have created an excel file and i am grouping the columns according to the type of information they provide with.

In [91]:
bureau_master=bureau_master.drop('SK_ID_BUREAU',axis=1)

In [92]:
bureau_master['bb_missing'] = (
    bureau_master['bb_oldest_mon']
    .isna()
    .astype('int8')
)

In [93]:
bureau_master['is_sold'] = (
    bureau_master['CREDIT_ACTIVE'] == 'Sold'
).astype('int8')

bureau_master['is_bad_debt'] = (
    bureau_master['CREDIT_ACTIVE'] == 'Bad debt'
).astype('int8')

In [94]:
money_cols = [

'AMT_CREDIT_SUM',
'AMT_CREDIT_SUM_DEBT',                          # sum, mean, max, std
'AMT_CREDIT_SUM_LIMIT',
'AMT_CREDIT_SUM_OVERDUE',
'AMT_CREDIT_MAX_OVERDUE',
'b_annuity_imp',
'b_exp_annuity'
]

In [95]:
# this creates 1 in each row and when we count, this gives the loan counts
bureau_master['loan_count']=1

In [96]:
max_overdue=['AMT_CREDIT_MAX_OVERDUE']          # mean, max (no point of sum)

In [97]:
time_cols = [
'DAYS_CREDIT',
'DAYS_CREDIT_ENDDATE',
'DAYS_ENDDATE_FACT',
'DAYS_CREDIT_UPDATE',           # min, max, mean, std
'b_credit_age',
'b_remaining_term',
'b_total_tenure',
'b_actual_tenure',
'b_tenure_gap',
'b_update_recency',
'b_log_curr_dpd',
'CREDIT_DAY_OVERDUE',
'CNT_CREDIT_PROLONG'
]

In [98]:
missing_cols = [
'bb_missing',
'b_annuity_missing',
'b_max_overdue_missing',
'b_debt_missing',               # sum, mean
'b_overdue_missing',
'b_curr_dpd_missing',
'b_prolong_missing'

]

In [99]:
flag_cols = [
'is_sold',
'is_bad_debt',
'b_has_overdue',
'b_has_curr_dpd',

'b_dpd30_flag',
'b_dpd60_flag',
'b_dpd90_flag',

'b_has_prolong',
'b_multi_prolong',
                                    # sum, mean
'b_expired_loan',
'b_has_actual_end',

'b_closed_late',
'b_closed_early',

'b_recent_30d',
'b_recent_90d',
'b_recent_180d',
'b_recent_365d'

]

In [100]:
interaction_cols = [

'b_credit_x_curr_dpd',
'b_credit_x_prolonged',

'b_debt_x_curr_dpd',
'b_debt_x_prolonged',
                                    # sum, mean, max
'b_overdue_x_curr_dpd',
'b_overdue_x_prolonged',

'b_prolong_x_curr_dpd',
'b_prolong_x_overdue',

'b_max_overdue_x_curr_dpd'

]

In [101]:
debt_state_cols = [

'b_active_debt',
'b_closed_debt',
'b_sold_debt',
'b_bad_debt_debt',
                                    # sum, mean, max
'b_active_overdue',
'b_closed_overdue',
'b_sold_overdue',
'b_bad_debt_overdue'

]

In [102]:
ratio_cols = [

'b_annuity_loan_ratio',

'b_max_overdue_to_credit',
'b_max_overdue_to_debt',
'b_current_to_max_overdue',

'b_paid_to_days',
'b_left_to_full',
'b_loan_to_tenure',

'b_curr_overdue_to_loan',
                                    # mean, max, std
'b_debt_to_credit',
'b_debt_to_days',
'b_debt_to_tenure',

'b_curr_overdue_to_debt',

'b_overdue_to_credit',
'b_overdue_to_debt',
'b_overdue_to_max_overdue',
'b_overdue_to_days',
'b_overdue_to_tenure',

'b_update_to_age',

'b_credit_per_day',
'b_debt_per_day',
'b_overdue_per_day'

]

In [103]:
bur_bal_history=['bb_oldest_mon',
'bb_latest_mon',
'bb_history_age',                   # mean, max, std
'bb_num_mon']

In [104]:
delinquency=[
'bb_max_default',
'bb_curr_stat',
'bb_mean_dpd'               # mean, max
]

In [105]:
npa_counts=[            # sum, mean, max
'bb_sma0',
'bb_sma1',
'bb_sma2',
'bb_npa'
]

In [106]:
npa_ratios=[            # mean, max, std
'bb_sma0_ratio',
'bb_sma1_ratio',
'bb_sma2_ratio',
'bb_npa_ratio'
]

In [107]:
# now the dictionary
agg_dict={}

# loan count
agg_dict['loan_count'] = ['sum']

# monetary
for col in money_cols:
    agg_dict[col] = ['sum', 'mean', 'max', 'std']

# overdue
for col in max_overdue:
    agg_dict[col] = ['mean', 'max']

# time
for col in time_cols:
    agg_dict[col] = ['min', 'max', 'mean', 'std']

# missing flags
for col in missing_cols:
    agg_dict[col] = ['sum', 'mean']

# risk flags
for col in flag_cols:
    agg_dict[col] = ['sum', 'mean']

# interaction
for col in interaction_cols:
    agg_dict[col] = ['sum', 'mean', 'max']

# debt state
for col in debt_state_cols:
    agg_dict[col] = ['sum', 'mean', 'max']

# ratios
for col in ratio_cols:
    agg_dict[col] = ['mean', 'max', 'std']

# bureau balance severity
for col in delinquency:
    agg_dict[col] = ['max', 'mean']

# bureau balance history
for col in bur_bal_history:
    agg_dict[col] = ['max', 'mean', 'std']

# bureau balance counts
for col in npa_counts:
    agg_dict[col] = ['sum', 'mean', 'max']

# bureau balance ratios
for col in npa_ratios:
    agg_dict[col] = ['mean', 'max', 'std']

In [108]:
bureau_customer = (
    bureau_master
    .groupby('SK_ID_CURR')
    .agg(agg_dict)
)
# flatten the aggregated columns
bureau_customer.columns = [
    f'BUREAU_{col}_{agg}'.upper()
    for col, agg in bureau_customer.columns
]

bureau_customer = bureau_customer.reset_index()

/var/folders/80/06sx31512gn_9yf7_8_qj0ph0000gn/T/ipykernel_1735/973220525.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bureau_customer = bureau_customer.reset_index()

In [109]:
bureau_customer

,SK_ID_CURR,BUREAU_LOAN_COUNT_SUM,BUREAU_AMT_CREDIT_SUM_SUM,BUREAU_AMT_CREDIT_SUM_MEAN,BUREAU_AMT_CREDIT_SUM_MAX,BUREAU_AMT_CREDIT_SUM_STD,BUREAU_AMT_CREDIT_SUM_DEBT_SUM,BUREAU_AMT_CREDIT_SUM_DEBT_MEAN,BUREAU_AMT_CREDIT_SUM_DEBT_MAX,BUREAU_AMT_CREDIT_SUM_DEBT_STD,...,BUREAU_BB_SMA0_RATIO_STD,BUREAU_BB_SMA1_RATIO_MEAN,BUREAU_BB_SMA1_RATIO_MAX,BUREAU_BB_SMA1_RATIO_STD,BUREAU_BB_SMA2_RATIO_MEAN,BUREAU_BB_SMA2_RATIO_MAX,BUREAU_BB_SMA2_RATIO_STD,BUREAU_BB_NPA_RATIO_MEAN,BUREAU_BB_NPA_RATIO_MAX,BUREAU_BB_NPA_RATIO_STD
0,100001,7,1453365.000,2.076236e+05,378000.00,122544.544510,596686.500,85240.928571,373239.00,137485.631124,...,0.019893,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100002,8,865055.565,1.081319e+05,450000.00,146075.557435,245781.000,49156.200000,245781.00,109916.604716,...,0.204094,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100003,4,1017400.500,2.543501e+05,810000.00,372269.465535,0.000,0.000000,0.00,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100004,2,189037.800,9.451890e+04,94537.80,26.728636,0.000,0.000000,0.00,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100005,3,657126.000,2.190420e+05,568800.00,303238.426806,568408.500,189469.500000,543087.00,306503.339003,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,3693858.660,2.841430e+05,765000.00,216131.351490,163071.000,16307.100000,163071.00,51567.578032,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305807,456250,3,3086459.550,1.028820e+06,2153110.05,973806.647980,2232040.095,744013.365000,1840308.48,969412.527734,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305808,456253,4,3960000.000,9.900000e+05,2250000.00,853024.032487,1795833.000,448958.250000,1624797.00,788028.037473,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305809,456254,1,45000.000,4.500000e+04,45000.00,NaN,0.000,0.000000,0.00,NaN,...,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN
305810,456255,11,3801919.500,3.456290e+05,900000.00,326337.215358,1534913.010,191864.126250,595102.50,219459.163931,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [110]:
missing_pct = (
    bureau_customer
    .isnull()
    .mean()
    .sort_values(ascending=False)
)

missing_pct.head(50)

BUREAU_B_OVERDUE_TO_MAX_OVERDUE_STD     0.914218
BUREAU_B_CURRENT_TO_MAX_OVERDUE_STD     0.914218
BUREAU_B_MAX_OVERDUE_TO_DEBT_STD        0.902682
BUREAU_B_OVERDUE_TO_MAX_OVERDUE_MAX     0.737413
BUREAU_B_CURRENT_TO_MAX_OVERDUE_MEAN    0.737413
BUREAU_B_CURRENT_TO_MAX_OVERDUE_MAX     0.737413
BUREAU_B_OVERDUE_TO_MAX_OVERDUE_MEAN    0.737413
BUREAU_B_MAX_OVERDUE_TO_DEBT_MEAN       0.673834
BUREAU_B_MAX_OVERDUE_TO_DEBT_MAX        0.673834
BUREAU_BB_OLDEST_MON_STD                0.617731
BUREAU_BB_HISTORY_AGE_STD               0.617731
BUREAU_BB_SMA0_RATIO_STD                0.617731
BUREAU_BB_NUM_MON_STD                   0.617731
BUREAU_BB_SMA1_RATIO_STD                0.617731
BUREAU_BB_NPA_RATIO_STD                 0.617731
BUREAU_BB_LATEST_MON_STD                0.617731
BUREAU_BB_SMA2_RATIO_STD                0.617731
BUREAU_B_OVERDUE_TO_DEBT_STD            0.610370
BUREAU_B_CURR_OVERDUE_TO_DEBT_STD       0.610370
BUREAU_B_MAX_OVERDUE_TO_CREDIT_STD      0.566785
BUREAU_BB_SMA1_MEAN                     0.560049
BUREAU_BB_SMA0_MAX                      0.560049
BUREAU_BB_SMA0_MEAN                     0.560049
BUREAU_BB_NUM_MON_MEAN                  0.560049
BUREAU_BB_NUM_MON_MAX                   0.560049
BUREAU_BB_HISTORY_AGE_MEAN              0.560049
BUREAU_BB_HISTORY_AGE_MAX               0.560049
BUREAU_BB_MEAN_DPD_MAX                  0.560049
BUREAU_BB_LATEST_MON_MEAN               0.560049
BUREAU_BB_LATEST_MON_MAX                0.560049
BUREAU_BB_OLDEST_MON_MEAN               0.560049
BUREAU_BB_OLDEST_MON_MAX                0.560049
BUREAU_BB_MEAN_DPD_MEAN                 0.560049
BUREAU_BB_SMA2_MEAN                     0.560049
BUREAU_BB_CURR_STAT_MEAN                0.560049
BUREAU_BB_CURR_STAT_MAX                 0.560049
BUREAU_BB_MAX_DEFAULT_MAX               0.560049
BUREAU_BB_SMA1_MAX                      0.560049
BUREAU_BB_MAX_DEFAULT_MEAN              0.560049
BUREAU_BB_SMA1_RATIO_MEAN               0.560049
BUREAU_BB_NPA_RATIO_MEAN                0.560049
BUREAU_BB_SMA0_RATIO_MAX                0.560049
BUREAU_BB_SMA0_RATIO_MEAN               0.560049
BUREAU_BB_NPA_MAX                       0.560049
BUREAU_BB_SMA2_RATIO_MEAN               0.560049
BUREAU_BB_NPA_MEAN                      0.560049
BUREAU_BB_SMA2_MAX                      0.560049
BUREAU_BB_NPA_RATIO_MAX                 0.560049
BUREAU_BB_SMA2_RATIO_MAX                0.560049
BUREAU_BB_SMA1_RATIO_MAX                0.560049
dtype: float64

In [111]:
bureau_customer.to_parquet(
'/Users/rageshwer/Goal ML/Projects/Home_Credit_Default_Risk/data/interim/bureau_agg1.parquet',index=False
)

Now, creating another separate feature engineered datasets for active and closed record of customers.

In [112]:
bureau_active=bureau_master[bureau_master['CREDIT_ACTIVE']=='Active'].copy()
bureau_closed=bureau_master[bureau_master['CREDIT_ACTIVE']=='Closed'].copy()

bureau_agg_active=bureau_active.groupby(
    ['SK_ID_CURR']
).agg(agg_dict)

bureau_agg_closed=bureau_closed.groupby(
    ['SK_ID_CURR']
).agg(agg_dict)

In [113]:
bureau_agg_active.columns = [
    f'ACTIVE_BUREAU_{col}_{agg}'.upper()
    for col, agg in bureau_agg_active.columns
]

bureau_agg_active = bureau_agg_active.reset_index()

bureau_agg_closed.columns = [
    f'CLOSED_BUREAU_{col}_{agg}'.upper()
    for col, agg in bureau_agg_closed.columns
]

bureau_agg_closed = bureau_agg_closed.reset_index()

/var/folders/80/06sx31512gn_9yf7_8_qj0ph0000gn/T/ipykernel_1735/902121830.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bureau_agg_active = bureau_agg_active.reset_index()
/var/folders/80/06sx31512gn_9yf7_8_qj0ph0000gn/T/ipykernel_1735/902121830.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bureau_agg_closed = bureau_agg_closed.reset_index()

In [114]:
bureau_agg_active

,SK_ID_CURR,ACTIVE_BUREAU_LOAN_COUNT_SUM,ACTIVE_BUREAU_AMT_CREDIT_SUM_SUM,ACTIVE_BUREAU_AMT_CREDIT_SUM_MEAN,ACTIVE_BUREAU_AMT_CREDIT_SUM_MAX,ACTIVE_BUREAU_AMT_CREDIT_SUM_STD,ACTIVE_BUREAU_AMT_CREDIT_SUM_DEBT_SUM,ACTIVE_BUREAU_AMT_CREDIT_SUM_DEBT_MEAN,ACTIVE_BUREAU_AMT_CREDIT_SUM_DEBT_MAX,ACTIVE_BUREAU_AMT_CREDIT_SUM_DEBT_STD,...,ACTIVE_BUREAU_BB_SMA0_RATIO_STD,ACTIVE_BUREAU_BB_SMA1_RATIO_MEAN,ACTIVE_BUREAU_BB_SMA1_RATIO_MAX,ACTIVE_BUREAU_BB_SMA1_RATIO_STD,ACTIVE_BUREAU_BB_SMA2_RATIO_MEAN,ACTIVE_BUREAU_BB_SMA2_RATIO_MAX,ACTIVE_BUREAU_BB_SMA2_RATIO_STD,ACTIVE_BUREAU_BB_NPA_RATIO_MEAN,ACTIVE_BUREAU_BB_NPA_RATIO_MAX,ACTIVE_BUREAU_BB_NPA_RATIO_STD
0,100001,3,884025.000,2.946750e+05,378000.00,1.112469e+05,596686.500,1.988955e+05,373239.00,1.509928e+05,...,0.030387,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100002,2,481988.565,2.409943e+05,450000.00,2.955787e+05,245781.000,1.228905e+05,245781.00,1.737934e+05,...,0.265165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100003,1,810000.000,8.100000e+05,810000.00,NaN,0.000,0.000000e+00,0.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100005,2,598626.000,2.993130e+05,568800.00,3.811122e+05,568408.500,2.842042e+05,543087.00,3.661155e+05,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,100008,1,267606.000,2.676060e+05,267606.00,NaN,240057.000,2.400570e+05,240057.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251810,456247,3,4113000.000,1.371000e+06,3118500.00,1.566054e+06,2193390.000,1.096695e+06,2193390.00,1.550961e+06,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251811,456249,2,405000.000,2.025000e+05,225000.00,3.181981e+04,163071.000,8.153550e+04,163071.00,1.153086e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251812,456250,2,2603110.050,1.301555e+06,2153110.05,1.204281e+06,2232040.095,1.116020e+06,1840308.48,1.024299e+06,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251813,456253,2,2610000.000,1.305000e+06,2250000.00,1.336432e+06,1795833.000,8.979165e+05,1624797.00,1.027964e+06,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251814,456255,5,2339532.000,4.679064e+05,810000.00,2.590869e+05,1534913.010,3.069826e+05,595102.50,2.002745e+05,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [115]:
bureau_agg_active.to_parquet(
'/Users/rageshwer/Goal ML/Projects/Home_Credit_Default_Risk/data/interim/bureau_agg_active.parquet',index=False
)
bureau_agg_closed.to_parquet(
'/Users/rageshwer/Goal ML/Projects/Home_Credit_Default_Risk/data/interim/bureau_agg_closed.parquet',index=False
)

In [116]:
del bureau_active
del bureau_closed

import gc
gc.collect()

2098

We trained our base line model, and to improve the scores, we are now using the different types of credit that a borrower has to merge into the application. The aggregation looses the information like what type of credit the customer has. A borrower with 5 cc of 50K is seen same as 2.5L mortgage loan which is more secure and less likely to default.

We will us only the top 5 features to create a new dataset with type of debt and merge the same with the application set.

In [117]:
bureau_type_cols=bureau_master['CREDIT_TYPE'].value_counts(ascending=False)
bureau_type_cols[:5].index
bureau_type_debt=pd.DataFrame()
bureau_type_debt.index=bureau_master['SK_ID_CURR'].unique()
for col_ in bureau_type_cols[:5].index:
    col = (col_.lower().replace(' ', '_').replace('-', '_'))
    bureau_type_debt[f'total_{col}_debt']=bureau_master[bureau_master['CREDIT_TYPE']==col_].groupby('SK_ID_CURR')['AMT_CREDIT_SUM'].sum()
    bureau_type_debt[f'total_{col}_count']=bureau_master[bureau_master['CREDIT_TYPE']==col_].groupby('SK_ID_CURR')['AMT_CREDIT_SUM'].count()
    bureau_type_debt[f'total_{col}_overdue']=bureau_master[bureau_master['CREDIT_TYPE']==col_].groupby('SK_ID_CURR')['AMT_CREDIT_SUM_OVERDUE'].sum()
    bureau_type_debt[f'total_{col}_max_overdue']=bureau_master[bureau_master['CREDIT_TYPE']==col_].groupby('SK_ID_CURR')['AMT_CREDIT_MAX_OVERDUE'].sum()

    bureau_type_debt[f'{col}_overdue_to_typedebt']=bureau_type_debt[f'total_{col}_overdue']/bureau_type_debt[f'total_{col}_debt']
    bureau_type_debt[f'{col}_max_overdue_to_typedebt']=bureau_type_debt[f'total_{col}_max_overdue']/bureau_type_debt[f'total_{col}_debt']
    bureau_type_debt[f'{col}_overdue_to_total']=bureau_type_debt[f'total_{col}_overdue']/(bureau_master[bureau_master['CREDIT_TYPE']==col_].groupby('SK_ID_CURR')['AMT_CREDIT_SUM'].sum())
    bureau_type_debt[f'{col}_max_overdue_to_total']=bureau_type_debt[f'total_{col}_max_overdue']/(bureau_master[bureau_master['CREDIT_TYPE']==col_].groupby('SK_ID_CURR')['AMT_CREDIT_SUM'].sum())
    bureau_type_debt[f'{col}_debt_share']=bureau_type_debt[f'total_{col}_debt']/(bureau_master[bureau_master['CREDIT_TYPE']==col_].groupby('SK_ID_CURR')['AMT_CREDIT_SUM'].sum())

In [118]:
bureau_type_debt.shape

(305811, 45)

In [119]:
bureau_type_debt.index.name='SK_ID_CURR'

In [120]:
bureau_type_debt.isna().mean().sort_values(ascending=False)

microloan_debt_share                       0.985072
microloan_max_overdue_to_total             0.985072
microloan_overdue_to_total                 0.985072
microloan_max_overdue_to_typedebt          0.985072
microloan_overdue_to_typedebt              0.985072
total_microloan_max_overdue                0.985072
total_microloan_overdue                    0.985072
total_microloan_count                      0.985072
total_microloan_debt                       0.985072
mortgage_overdue_to_total                  0.944891
mortgage_overdue_to_typedebt               0.944891
mortgage_max_overdue_to_typedebt           0.944891
mortgage_max_overdue_to_total              0.944891
mortgage_debt_share                        0.944891
total_mortgage_max_overdue                 0.944888
total_mortgage_overdue                     0.944888
total_mortgage_count                       0.944888
total_mortgage_debt                        0.944888
car_loan_max_overdue_to_typedebt           0.925457
car_loan_debt_share                        0.925457
car_loan_max_overdue_to_total              0.925457
car_loan_overdue_to_total                  0.925457
car_loan_overdue_to_typedebt               0.925457
total_car_loan_max_overdue                 0.925457
total_car_loan_overdue                     0.925457
total_car_loan_count                       0.925457
total_car_loan_debt                        0.925457
credit_card_debt_share                     0.390408
credit_card_overdue_to_typedebt            0.390300
credit_card_overdue_to_total               0.390300
credit_card_max_overdue_to_total           0.388272
credit_card_max_overdue_to_typedebt        0.388272
total_credit_card_debt                     0.346116
total_credit_card_count                    0.346116
total_credit_card_overdue                  0.346116
total_credit_card_max_overdue              0.346116
consumer_credit_debt_share                 0.062607
consumer_credit_max_overdue_to_total       0.062607
consumer_credit_overdue_to_total           0.062607
consumer_credit_max_overdue_to_typedebt    0.062607
consumer_credit_overdue_to_typedebt        0.062607
total_consumer_credit_overdue              0.062594
total_consumer_credit_count                0.062594
total_consumer_credit_max_overdue          0.062594
total_consumer_credit_debt                 0.062594
dtype: float64

In [121]:
bureau_type_debt.to_parquet('/Users/rageshwer/Goal ML/Projects/Home_Credit_Default_Risk/data/interim/bureau_debt_type.parquet')